name: erlang_etf_parser
description: A Dart package to parse Erlang External Term Format (ETF) binary data.
version: 0.0.2
homepage: https://github.com/nghienp/erlang_etf_parser
repository: https://github.com/nghienp/erlang_etf_parser.git
environment:
  sdk: ^3.0.0

dev_dependencies:
  test: any
  pedantic: any